// ---appInfo
export const CHANGE_RESPONSIVE = 'CHANGE_RESPONSIVE';
export const UPDATE_PATH = 'UPDATE_PATH';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_PARAMS = 'UPDATE_PARAMS';

// ---master
export const UPDATE_CURRENT_PRODUCTS = 'UPDATE_CURRENT_PRODUCTS';
export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_PAGE_AND_SIZE = 'UPDATE_PAGE_AND_SIZE';
export const UPDATE_ONE_PRODUCT = 'UPDATE_ONE_PRODUCT';
export const PRODUCTS_NOT_UPDATED = 'PRODUCTS_NOT_UPDATED';
export const CHANGE_FIRST_RENDER = 'CHANGE_FIRST_RENDER';
export const RESET_SEARCH_PARAMS = 'RESET_SEARCH_PARAMS';

// ---home
export const GET_PUBLIC_HOME = 'GET_PUBLIC_HOME';

export default null;
